version: '3.8'

services:
  app:
    restart: always
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    environment:
      - GIN_MODE=release
      - LOG_LEVEL=warn
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  pocketbase:
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    restart: always
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.1'
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

  nginx:
    profiles:
      - ""
    restart: always
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.1'